// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWrwznawmt3i3vRFwARKpaUbMGqWlqkV0',
    appId: '1:262213187805:web:edab0d4d5b8130e3000334',
    messagingSenderId: '262213187805',
    projectId: 'fir-notesapp-ff9e4',
    authDomain: 'fir-notesapp-ff9e4.firebaseapp.com',
    storageBucket: 'fir-notesapp-ff9e4.firebasestorage.app',
    measurementId: 'G-3D63PQY4EW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjwtyHRYYsJiXepiTJA9APp08ExMP3xOE',
    appId: '1:262213187805:android:71268215412f49fb000334',
    messagingSenderId: '262213187805',
    projectId: 'fir-notesapp-ff9e4',
    storageBucket: 'fir-notesapp-ff9e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwpIeRzD_d59MmVljHaiOAYq8P-m6e3qc',
    appId: '1:262213187805:ios:b10200d0757f4d72000334',
    messagingSenderId: '262213187805',
    projectId: 'fir-notesapp-ff9e4',
    storageBucket: 'fir-notesapp-ff9e4.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwpIeRzD_d59MmVljHaiOAYq8P-m6e3qc',
    appId: '1:262213187805:ios:b10200d0757f4d72000334',
    messagingSenderId: '262213187805',
    projectId: 'fir-notesapp-ff9e4',
    storageBucket: 'fir-notesapp-ff9e4.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWrwznawmt3i3vRFwARKpaUbMGqWlqkV0',
    appId: '1:262213187805:web:82088af452c24803000334',
    messagingSenderId: '262213187805',
    projectId: 'fir-notesapp-ff9e4',
    authDomain: 'fir-notesapp-ff9e4.firebaseapp.com',
    storageBucket: 'fir-notesapp-ff9e4.firebasestorage.app',
    measurementId: 'G-DS574XWXFB',
  );
}
